### ISSUE TITLE
Error, in IE v=11 broken component where I put this plugin

### ISSUE THREAD

**Issue by serhiybilous** [zh-rocco/vue-auto-storage#3]
**Describe the bug**
in IE v=11 plugin broken my component. (Component not builded)
And not any errors in console.

**To Reproduce**
Put this code in component 
`import Vue from "vue"`
`import VueAutoStorage from "vue-auto-storage"`
`Vue.use(VueAutoStorage)`
Use in component
`autoStorage: ['client', 'step']`

**My decision**
Move all plugin to application (local)
And then it works

Can you please this problem and fix it

**Comment by zh-rocco** [comment]
@serhiybilous Sorry, I haven't done enough testing. I have fixed it. You can [try it](https://zh-rocco.github.io/vue-auto-storage/) in IE browser.
